// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxsojctheffiiywggeey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4c29qY3RoZWZmaWl5d2dnZWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTQ1NDMsImV4cCI6MjA2MDk3MDU0M30.taouXWO92fvGJLMLGLV96ysvRWDxjilDH72kKJ84TZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);